using Microsoft.EntityFrameworkCore;
using Microsoft.Data.SqlClient;
using System.Configuration;
using CDB.Model;
using log4net;

namespace CDB
{
    public class DataWrapper : IDataWrapper
    {
        private static readonly ILog log = LogManager.GetLogger(typeof(DataWrapper));
        public CdbContext context;
        public static string DatabaseConnectionString = string.Empty;

        static DataWrapper()
        {
            GetConnectionStringFromConfig();

            if (string.IsNullOrEmpty(DatabaseConnectionString))
            {
                throw new ConfigurationErrorsException("Unable to determine database connection string from configuration file!");
            }
            else
            {
                log.Debug($"Database connection string successfully initialised as {DatabaseConnectionString}.");
            }
        }

        public DataWrapper()
        {
            var connectionStringBuilder = new SqlConnectionStringBuilder();
            connectionStringBuilder.ConnectionString = DatabaseConnectionString;
            DbContextOptions<CdbContext> options = SqlServerDbContextOptionsExtensions.UseSqlServer(new DbContextOptionsBuilder<CdbContext>(), DatabaseConnectionString).Options;
            this.context = new CdbContext(options);
        }

        public static void GetConnectionStringFromConfig()
        {
            var connectionStringCollection = ConfigurationManager.ConnectionStrings;

            foreach (ConnectionStringSettings connectionStringSettings in connectionStringCollection)
            {
                if (connectionStringSettings.Name == "CDBConnectionString")
                {
                    DatabaseConnectionString = connectionStringSettings.ConnectionString;
                }
            }
        }

        public List<Customer> SelectAllCustomers()
        {
            try
            {
                List<Customer> customerList = context.Customers.ToList();
                log.Debug($"Customers successfully queried from CDB database. {customerList.Count} results returned.");
                return customerList;
            }
            catch (Exception exception)
            {
                log.Error(exception);
                throw;
            }
        }

        /// <summary>
        /// Inserts a new customer into the database by invoking a stored procedure.
        /// </summary>
        /// <param name="companyName"></param>
        /// <param name="businessContact"></param>
        /// <param name="emailAddress"></param>
        /// <param name="contactNumber"></param>
        /// <returns></returns>
        public int InsertNewCustomer(Customer customer)
        {
            try
            {
                context.Customers.Add(customer);
                int dbSaveResult = context.SaveChanges();
                log.Debug($"Status code {dbSaveResult} returned attempting to insert customer. New customer ID is {customer.Id}");
                return dbSaveResult;
            }
            catch (Exception exception)
            {
                log.Error(exception);
                throw;
            }
        }

        public int UpdateCustomer(int id)
        {
            Customer customerToUpdate = this.context.Customers.Where(customer => customer.Id == id).First();

            try
            {
                int dbUpdateResult = context.SaveChanges();
                this.context.Entry(customerToUpdate).Reload();
                log.Debug($"Status code {dbUpdateResult} returned. Attempting to update customer with ID {id}.");
                return dbUpdateResult;
            }
            catch (Exception exception)
            {
                log.Error(exception);
                throw;
            }
        }

        public void LoadSubscriptions(int customerId)
        {
            try
            {
                // Grab the customer object.
                Customer customer = this.context.Customers.Where(customer => customer.Id == customerId).First();

                // Load the subscriptions.
                this.context.Entry(customer).Collection(customer => customer.Subscriptions).Load();

                // For each of the subscriptions loaded, load the service from the data context..
                foreach (Subscription sub in customer.Subscriptions)
                {
                    this.context.Entry(sub).Reference(sub => sub.Service).Load();
                }
            }
            catch (Exception exception)
            {
                log.Error(exception);
                throw;
            }
        }

        /// <summary>
        /// Selects all the Services.
        /// </summary>
        /// <returns>A List of Services generated by the Data Context.</returns>
        public List<Service> SelectAllServices()
        {
            try
            {
                List<Service> services = this.context.Services.ToList();
                log.Debug($"Services successfully obtained from Data Context. {services.Count} services returned.");
                return services;
            }
            catch (Exception exception)
            {
                log.Error(exception);
                throw;
            }
        }

        public int InsertNewService(Service service)
        {
            try
            {
                this.context.Services.Add(service);
                int dbSaveResult = this.context.SaveChanges();
                log.Debug($"New service record saved in CDB Database. Status code returned was {dbSaveResult}. New Service ID is {service.Id}.");
                return dbSaveResult;
            }
            catch (Exception exception)
            {
                log.Error(exception);
                throw;
            }
        }

        public int UpdateService(int serviceId)
        {
            try
            {
                Service serviceToUpdate = this.context.Services.Where(service => service.Id == serviceId).First();
                int saveResult = this.context.SaveChanges();
                this.context.Entry(serviceToUpdate).Reload();
                log.Debug($"Status code {saveResult} returned from CDB database updating service with ID {serviceId}.");
                return saveResult;
            }
            catch (Exception exception)
            {
                log.Error(exception);
                throw;
            }
        }
    }
}
